# Generated by Django 6.0.4 on 2026-05-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
