# Generated by Django 6.0.4 on 2026-05-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_size',
            field=models.CharField(blank=True, choices=[('1-10', '1–10 employees'), ('11-50', '11–50 employees'), ('51-200', '51–200 employees'), ('201-500', '201–500 employees'), ('501-1000', '501–1000 employees'), ('1001+', '1001+ employees')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='founded_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, choices=[('technology', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('retail', 'Retail & E-commerce'), ('manufacturing', 'Manufacturing'), ('media', 'Media & Entertainment'), ('real_estate', 'Real Estate'), ('consulting', 'Consulting'), ('logistics', 'Logistics & Supply Chain'), ('hospitality', 'Hospitality & Tourism'), ('energy', 'Energy & Utilities'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='company',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
