# Generated by Django 6.0.4 on 2026-05-15 07:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_company_members_companymember'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='companies', through='accounts.CompanyMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
