# Generated by Django 6.0.4 on 2026-06-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rfp_rfpinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='sub_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
