# Generated by Django 6.0.4 on 2026-06-03 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_jobopening_category_jobopening_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobopening',
            name='category',
        ),
        migrations.RemoveField(
            model_name='jobopening',
            name='sub_category',
        ),
    ]
