# Generated by Django 6.0.4 on 2026-06-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_category_subcategory_from_jobopening'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfp',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rfp',
            name='sub_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
