# Generated by Django 6.0.4 on 2026-06-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_add_category_subcategory_to_rfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='key_skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
