# Generated by Django 6.0.4 on 2026-06-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_jobpostplan_jobopening_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostplan',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
