# Generated by Django 6.0.4 on 2026-06-25 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='freelancer_availability',
            field=models.CharField(default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='freelancer_currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_freelancer',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio_projects/')),
                ('project_url', models.URLField(blank=True, null=True)),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.profile')),
            ],
        ),
    ]
