# Generated by Django 6.0.4 on 2026-06-30 04:40

import uuid
from django.db import migrations, models


def gen_uuid(apps, schema_editor):
    Company = apps.get_model('accounts', 'Company')
    for row in Company.objects.all():
        row.public_id = uuid.uuid4()
        row.save(update_fields=['public_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_profile_freelancer_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='company',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
