# Generated by Django 6.0.4 on 2026-07-06 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_companyreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreview',
            name='rfp_interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_reviews', to='accounts.rfpinterest'),
        ),
        migrations.AddField(
            model_name='rfpinterest',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FreelancerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('review_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_freelancer_reviews', to=settings.AUTH_USER_MODEL)),
                ('rfp_interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freelancer_reviews', to='accounts.rfpinterest')),
            ],
        ),
    ]
