# Generated by Django 6.0.4 on 2026-07-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_companyreview_rfp_interest_rfpinterest_is_reviewed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreview',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='freelancerreview',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
