# Generated by Django 6.0.4 on 2026-07-20 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_companyreview_is_flagged_freelancerreview_is_flagged'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='accounts.company')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
