# Generated by Django 6.0.4 on 2026-07-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_companyfaq'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreview',
            name='flag_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancerreview',
            name='flag_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='flag_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rfp',
            name='flag_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfp',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
