# Generated by Django 6.0.4 on 2026-07-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_companyreview_flag_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreview',
            name='review_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='freelancerreview',
            name='review_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='job_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rfp',
            name='rfp_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
