# Generated by Django 6.0.4 on 2026-07-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_companyreview_review_id_freelancerreview_review_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
