# Generated by Django 6.0.4 on 2026-07-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_company_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfpinterest',
            name='quotation_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
