# Generated by Django 6.0.4 on 2026-07-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_rfpinterest_quotation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymember',
            name='access_role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('hr', 'HR Manager'), ('accountant', 'Accountant'), ('user', 'Employee')], default='user', max_length=20),
        ),
    ]
