# Generated by Django 6.0.4 on 2026-07-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_companymember_access_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
