# Generated by Django 6.0.4 on 2026-07-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_jobopening_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfp',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
