# Generated by Django 6.0.4 on 2026-07-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_rfp_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
    ]
