# Generated by Django 6.0.4 on 2026-07-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_jobopening_is_frozen'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='rfp_response_days',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
