# Generated by Django 6.0.4 on 2026-08-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_company_rfp_response_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreview',
            name='flag_status',
            field=models.CharField(blank=True, choices=[('unresolved', 'Unresolved'), ('resolved', 'Resolved')], default='unresolved', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='freelancerreview',
            name='flag_status',
            field=models.CharField(blank=True, choices=[('unresolved', 'Unresolved'), ('resolved', 'Resolved')], default='unresolved', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='flag_status',
            field=models.CharField(blank=True, choices=[('unresolved', 'Unresolved'), ('resolved', 'Resolved')], default='unresolved', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rfp',
            name='flag_status',
            field=models.CharField(blank=True, choices=[('unresolved', 'Unresolved'), ('resolved', 'Resolved')], default='unresolved', max_length=20, null=True),
        ),
    ]
