# Generated by Django 6.0.4 on 2026-08-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_companyreview_flag_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyreview',
            name='flag_status',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('unresolved', 'Unresolved'), ('resolved', 'Resolved')], default='none', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='freelancerreview',
            name='flag_status',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('unresolved', 'Unresolved'), ('resolved', 'Resolved')], default='none', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='flag_status',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('unresolved', 'Unresolved'), ('resolved', 'Resolved')], default='none', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rfp',
            name='flag_status',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('unresolved', 'Unresolved'), ('resolved', 'Resolved')], default='none', max_length=20, null=True),
        ),
    ]
