# Generated by Django 6.0.3 on 2026-09-03 07:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_companyreview_flag_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreview',
            name='flagged_by',
            field=models.ManyToManyField(blank=True, related_name='flagged_company_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freelancerreview',
            name='flagged_by',
            field=models.ManyToManyField(blank=True, related_name='flagged_freelancer_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='flagged_by',
            field=models.ManyToManyField(blank=True, related_name='flagged_job_openings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rfp',
            name='flagged_by',
            field=models.ManyToManyField(blank=True, related_name='flagged_rfps', to=settings.AUTH_USER_MODEL),
        ),
    ]
