# Generated by Django 6.0.3 on 2026-09-10 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_message_company_alter_message_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfpinterest',
            name='applicant_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_rfp_interests', to='accounts.company'),
        ),
    ]
