# Generated by Django 6.0.4 on 2026-09-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_companymedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
