# Generated by Django 6.0.4 on 2026-09-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_add_category_to_job_opening'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='sub_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
