# Generated by Django 6.0.4 on 2026-10-01 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_jobopening_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('user_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('action_type', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('PROFILE_SWITCH', 'Switched Profile/Mode'), ('COMPANY_SWITCH', 'Switched Active Company'), ('JOB_APPLY', 'Applied for Job'), ('JOB_CREATE', 'Posted Job Opening'), ('JOB_UPDATE', 'Updated Job Opening'), ('RFP_CREATE', 'Posted RFP'), ('RFP_UPDATE', 'Updated RFP'), ('RFP_INTEREST', 'Submitted RFP Proposal/Interest'), ('REVIEW_POST', 'Posted Review'), ('PROFILE_UPDATE', 'Updated Profile Information'), ('PAGE_VIEW', 'Page View / Navigation'), ('OTHER', 'Other Action')], db_index=True, max_length=50)),
                ('action_title', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.CharField(blank=True, db_index=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
